### PR TITLE
Fix `appBackgroundColor` theme property handling

### LINKED ISSUE #2439: `appBackgroundColor` config setting is not correctly applied
On https://elifesciences.org/articles/55164 the Hypothesis client is configured with a custom `appBackgroundColor` setting:

Screenshot 2020-08-14 at 10 02 46

However this is not used for the sidebar's background color as it should be. The background color is the default grey instead of white:

Screenshot 2020-08-14 at 09 58 59

There is also an issue with the background color of the right-hand side of the "Post to" button.

### PR DESCRIPTION
**Pull request by robertknight**
This fixes the regressions in #2143.

- Fix an incorrect call to `applyTheme` which passed an invalid theme
property name (`backgroundColor` instead of `appBackgroundColor`). This is a regression from when this component was converted from AngularJS to Preact in 7bbb8a6.
- Improve the type definitions of `applyTheme` and add a test to help catch
such mistakes in future.
- Fix `ctaBackgroundColor` not being applied correctly to the right-hand side of the "Post to <group name>" button

Tested manually with this diff to the dev server config:

```diff
diff --git a/dev-server/templates/client-config.js.mustache b/dev-server/templates/client-config.js.mustache
index 080d8657d..dde7b0ce3 100644
--- a/dev-server/templates/client-config.js.mustache
+++ b/dev-server/templates/client-config.js.mustache
@@ -2,6 +2,11 @@
   var appHost = document.location.hostname;
   window.hypothesisConfig = function() {
     return {
+      branding: {
+        appBackgroundColor: 'white',
+        ctaBackgroundColor: 'red',
+        ctaTextColor: 'yellow',
+      },
       // enableExperimentalNewNoteButton: true,
       // showHighlights: 'always',
       // theme: 'clean',
@@ -29,4 +34,4 @@
   var embedScript = document.createElement('script');
   embedScript.src = '{{{clientUrl}}}'.replace('{current_host}', document.location.hostname);
   document.body.appendChild(embedScript);
-</script>
\ No newline at end of file
+</script>
```
Fixes #2439

### CODE REVIEW

File: src/sidebar/components/annotation-publish-control.js [hunk 1]
```diff
@@ -15,6 +15,7 @@ import SvgIcon from '../../shared/components/svg-icon';
 /**
  * @typedef {import('../../types/api').Annotation} Annotation
  * @typedef {import('../../types/config').MergedConfig} MergedConfig
+ * @typedef {import('../util/theme').ThemeProperty} ThemeProperty
```
Comment (lyzadanger) [inline src/sidebar/components/annotation-publish-control.js:18]: Help me with a confusion! I see this `typedef` imported here, but how is it used?

Comment (lyzadanger) [reply src/sidebar/components/annotation-publish-control.js:18]: ...I'm wondering if this doesn't need to be imported here...?

Comment (robertknight) [reply src/sidebar/components/annotation-publish-control.js:18]: Oh, indeed! This is left-over from an earlier version of this PR. I'll remove it.
