### PR TITLE
Fix bug with asynchronous range highlighting

### LINKED ISSUE #2502: Bug: Resizing can cause anchored annotations to disappear in PDFs
I believe that this issue is pre-existing, but is considerably exacerbated when in the new side-by-side mode.

To reproduce (I'm in Chrome, FWIW):

1. Load up a PDF in side-by-side mode (hint: you can do this on Via3 currently. Hit me up if you need instructions). See that the PDF has some annotations visible.
2. Ensure PDF zoom is set to "Automatic" (At least for Chrome)
3. Resize the browser window some
4. Notice that highlights/anchored annotations disappear from the PDF document

*Edited: This bug is orthogonal to side-by-side mode. Resizing a PDF with PDF.js and the client in any mode will cause this error eventually. It happens more frequently in side by side mode because more resizing is happening. I've updated the issue title to reflect this.*

### PR DESCRIPTION
**Pull request by lyzadanger**
This PR attempts to fix a bug manifesting as a thrown Error and the disappearance of highlights from PDF documents after multiple resizes or other DOM-structure changes that fire the `MutationObserver` callback in the `PDF` plugin.

I shall elaborate on all things: explanation, motivation of approach, etc. after we verify that this approach is feasible.

(Edited: commit messages are now elaborated).

Fixes #2502

### CODE REVIEW

File: src/annotator/plugin/pdf.coffee [hunk 1]
```diff
@@ -16,7 +17,7 @@ module.exports = class PDF extends Plugin
 
     @pdfMetadata = new PDFMetadata(PDFViewerApplication)
 
-    @observer = new MutationObserver((mutations) => this._update())
+    @observer = new MutationObserver(debounce(this._update.bind(this), 100))
```
Comment (lyzadanger) [inline src/annotator/plugin/pdf.coffee:20]: I pulled `100ms` out of a hat.

**Review by robertknight — APPROVED** [review]
LGTM. I have done some basic testing locally but only with lightly annotated pages.
