### PR TITLE
Wait for URL change after calling `history.back()`

### LINKED ISSUE #5004: Sporadic test failure in `normalizeURI`
This test failure has occurred a couple of times recently:

```
FAILED TESTS:
  annotator.util.url
    normalizeURI
      ✖ resolves relative URLs against the document URI, if no base URI is provided
        Chrome Headless 107.0.5304.87 (Linux x86_64)
      AssertionError: expected 'http://localhost:9876/books/abc/epub/…' to equal 'http://localhost:9876/books/abc/epub/…'

      + expected - actual

      -http://localhost:9876/books/abc/epub/OPS/xhtml/foo.html
      +http://localhost:9876/books/abc/epub/OPS/xhtml/chapter_001.html?ignoreme#cfi=/foo/foo.html
      
    at Context.<anonymous> (/home/runner/work/client/client/src/annotator/util/test/url-test.js:13:14)
```

From Slack thread: https://hypothes-is.slack.com/archives/C1M8NH76X/p1669119743405089

### PR DESCRIPTION
**Pull request by robertknight**
Avoid the temporary URL navigation done by VitalSource tests from affecting other tests by pausing in `afterEach` until the async `history.back()` operation has completed. Note this API doesn't return a promise. [Waiting for `popstate`](https://developer.mozilla.org/en-US/docs/Web/API/History/back) is how MDN recommends waiting.

A more elaborate solution would be to change the VitalSource integration to read from an injected fake location in tests. I might pursue that if this change runs into problems.

Fixes #5004

### CODE REVIEW

File: src/annotator/integrations/test/vitalsource-test.js [hunk 1]
```diff
@@ -496,8 +496,14 @@ describe('annotator/integrations/vitalsource', () => {
         history.pushState({}, '', bookURI);
       });
 
-      afterEach(() => {
+      afterEach(async () => {
```
Comment (lyzadanger) [inline src/annotator/integrations/test/vitalsource-test.js:499]: Achievement unlocked! `async` `afterEach`

**Review by lyzadanger — APPROVED** [review]
👍🏻
