### PR TITLE
Work around Chrome bug causing sidebar to become invisible

### LINKED ISSUE #516: Transparent sidebar after following a direct link in Chrome v60-61
Heather, Sean H and myself have all been able to reproduce an issue where the client loads but the sidebar application is transparent.

[Internal Slack discussion](https://hypothes-is.slack.com/archives/C03QZM0K4/p1501774682420282)

Upstream bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=753314

Reduced test case: https://github.com/hypothesis/chrome-invisible-iframe-bug

### Steps to reproduce
1. In a Chrome browser with the Hypothesis extension installed, go to https://www.nytimes.com/2017/08/02/us/politics/trump-conservative-republicans.html
2. Click on the link in the sidebar that points to https://hyp.is/PhJttnhhEee3ohv_EsiIPA/www.nytimes.com/2017/08/02/us/politics/trump-immigration.html
3.Wait for the new tab to load and the sidebar to open

### Expected behaviour
The sidebar application is visible.

### Actual behaviour

The sidebar iframe is there in the DOM, but transparent:

screenshot 2017-08-03 17 45 12

### Browser/system information
Chrome 61.0.3163.25 (me), Chrome 60.0.3112.78 (seanh), Chrome Canary 62.0.3175.0 (me)

### Additional details

The sidebar content re-appears if I do any of the following:

1. Toggle the visibility of the iframe by applying and then removing `display: none`
2. Switch to another tab and back again

### PR DESCRIPTION
**Pull request by robertknight**
Work around a Chrome bug [1] that can cause the sidebar to become
invisible if:

 1. The sidebar app is loaded from a Chrome extension AND
 2. The current tab was opened by clicking a link inside the sidebar
    app in a different tab.

When the issue occurs, the sidebar web app loads and runs normally but
is just not visible on screen. Temporarily hiding and showing the iframe
resolves the problem. At the point when the temporary hide & show
occurs, the iframe is positioned to the right of the viewport, so the
user does not see the visibility change.

Fixes #516

[1] https://bugs.chromium.org/p/chromium/issues/detail?id=753314

### CODE REVIEW

**Comment by dwhly** [comment]
Turns out it's an older Chrome bug:  https://bugs.chromium.org/p/chromium/issues/detail?id=638375

**Comment by robertknight** [comment]
From the bug report above, it turns out that there is an alternative and probably better way to fix the problem: Make sure that all links in the sidebar disown their opener when clicked (by adding `rel="noopener"` to it or intercepting the link click and performing the same action dynamically).

This enables Chrome to use a separate process for the instance of Hypothesis in the newly opened tab, because that Hypothesis instance no longer has synchronous access to the Hypothesis sidebar in the opening tab (via `window.top.opener`). According to the Chrome devs in that bug report, this should fix the problem in all cases.

This method might be better because it avoids the potential overheads that the `display` switching might toggle or potential unfortunate interactions between the timeout added here and other parts of the app.

**Comment by seanh** [comment]
@robertknight `rel="noopener"` sounds better to me, too. It seems like it would be a security improvement as well - when the user clicks on a (possibly user-created link) in the sidebar and it opens in a new tab, I don't think we want the JavaScript running on that arbitrary third-party site in the new tab to have access to our clients `window`. I believe this could be used to, for example, change the URL of our iframe back in the original tab. (iirc this issue has been fixed in current versions of _some_ browsers, but still)

**Comment by robertknight** [comment]
@seanh - Thanks for the feedback, I've revised the PR accordingly. Adding `rel="noopener"` to every link in the client manually would be a painful process, so I've opted to add a piece of code that does it _just before_ a link click is handled, if that link would open in a new tab/window (triggered by having `target="_blank"`).

**Comment by seanh** [comment]
Confirmed that I can still reproduce the issue on master and that this branch fixes it

File: src/sidebar/util/disable-opener-for-external-links.js [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+ * This makes links with `target="blank"` attributes act as if they also had
+ * the `rel="noopener"` [1] attribute set.
+ *
+ * In addition to preventing tab-jacking [2], this also enables multi-process
+ * browsers to more easily use a new process for instances of Hypothesis in the
+ * newly-opened tab and works around a bug in Chrome [3]
+ *
+ * [1] https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types#noopener
+ * [2] https://mathiasbynens.github.io/rel-noopener/
+ * [3] https://bugs.chromium.org/p/chromium/issues/detail?id=753314
```
Comment (seanh) [inline src/sidebar/util/disable-opener-for-external-links.js]: Very nice docstring, which is important for a kind of obscure fix like this
