### PR TITLE
Fix case-sensitivity issue with rendering suggested tags

### LINKED ISSUE #2547: remembered tags are doubled
When the tag list in localStorage is like this:

["RRIDCUR:Validated","va","RRID:Addgene_12259","RRID:CVCL_2426","RRIDCUR:Unrecognized","PMID:32894207","PMID:32905778","PMID:32915137","PMID:32935086","RRID:AB_621848","RRIDCUR:Missing"]

The remembered tag list in the client is like this:

image

### PR DESCRIPTION
**Pull request by lyzadanger**
The `TagEditor` component formerly did not take casing into account
in its formatting function for suggested tags. The match should be
case-insensitive in the formatter, as it is in the service that does
the filtering of tags.

This is fixed in two ways:

1. Make substring matching in the formatting function case-insensitive.
   Render the substring match according to the suggested tag's casing.
   Fixes this issue specifically.
2. Provide a fallback in the formatter for when the input text does not
   "seem" to match the suggested `item`. In these cases, just render the
   suggested tag as-is. This will prevent the formatter from spazzing
   out if its notion of matching differs from the tag-service's in
   any future case.

Fixes #2547

### CODE REVIEW

File: src/sidebar/components/test/tag-editor-test.js [hunk 1]
```diff
@@ -116,6 +116,56 @@ describe('TagEditor', function () {
...
+  it('shows case-insensitive matches to suggested tags', () => {
+    fakeTagsService.filter.returns(['fine AArdvark', 'AAArgh']);
+    const wrapper = createComponent();
+    wrapper.find('input').instance().value = 'aa';
+    typeInput(wrapper);
+
+    const formattingFn = wrapper.find('AutocompleteList').prop('listFormatter');
+    const tagList = wrapper.find('AutocompleteList').prop('list');
+
+    const firstSuggestedTag = mount(formattingFn(tagList[0]))
```
Comment (lyzadanger) [inline src/sidebar/components/test/tag-editor-test.js:128]: The `formattingFn` returns a `vnode`, and I need a wrapper to work with here... let me know if this is not kosher and/or if there is a better way here.

This bit is a little fiddly to test as it's interplay between two components: `TagEditor` owns the callback, but `AutocompleteList` does the eventual rendering.

File: src/sidebar/components/tag-editor.js [hunk 2]
```diff
@@ -244,15 +244,32 @@ function TagEditor({
...
-    const suffix = item.slice(item.indexOf(curVal) + curVal.length);
+  const formatSuggestedItem = item => {
+    // filtering of tags is case-insensitive
+    const curVal = pendingTag().toLowerCase();
+    const suggestedTag = item.toLowerCase();
+    const matchIndex = suggestedTag.indexOf(curVal);
+
+    // If the current input doesn't seem to match the suggested tag,
+    // just render the tag as-is.
+    if (matchIndex === -1) {
```
Comment (lyzadanger) [inline src/sidebar/components/tag-editor.js:255]: I hope this doesn't seem too hand-wavey.

File: src/sidebar/components/test/tag-editor-test.js [hunk 3]
```diff
@@ -116,6 +116,56 @@ describe('TagEditor', function () {
...
+  });
+
+  it('shows suggested tags as-is if they do not seem to match the input', () => {
+    // This case addresses a situation in which a substring match isn't found
+    // for the current input text against a given suggested tag. This should not
+    // happen in practice—i.e. filtered tags should match the current input—
+    // but there is no contract that the tags service filtering uses the same
+    // "matching" as the component, so we should be able to handle cases where
+    // there doesn't "seem" to be a match by just rendering the suggested tag
+    // as-is.
```
Comment (robertknight) [inline src/sidebar/components/test/tag-editor-test.js:148]: This comment is helpful. It also suggests an alternative possibility where the tag-searching API returns both the matching tags and the corresponding substrings within the tag. I think this is fine for the moment though.

**Review by robertknight — APPROVED** [review]
LGTM. Good comments :)

File: src/sidebar/components/test/tag-editor-test.js (hunk 3 above)
Comment (lyzadanger) [reply src/sidebar/components/test/tag-editor-test.js:148]: Yeah, the same thing occurred to me...
