### PR TITLE
Provide a UI path for sharing when a page's or annotation's URI is not web-accessible

### LINKED ISSUE #2786: Share panel generates invalid hyp.is / bouncer links for local PDF files
### Steps to reproduce
1. Open a local PDF file in Chrome
2. Activate the Hypothesis browser extension
3. Click on the "Share" icon in the top navigation bar

### Expected behaviour

The link shown in the panel should only reference HTTP URIs which bouncer can actually send the user to, or URIs in some other scheme which bouncer could resolve to an HTTP URI.

If no HTTP URL is available then the dialog should either show some suitable explanation or fall back to generating an activity page link to the group's activity page.

### Actual behaviour

A hyp.is link is generated which tries to direct the user to a URI which is the PDF fingerprint. For example: https://hyp.is/go?url=urn%3Ax-pdf%3A102c7f4b4df6b006687f35b60cf013ab&group=abcdef

Share link for local PDF file

### PR DESCRIPTION
**Pull request by lyzadanger**
There has been some (understandable) ongoing confusion around share links for single annotations or sets of annotations that pertain to a URI that is not available on the web. Specifically, it's confusing if one annotates a local PDF and then attempts to share a single annotation or a set of annotations on that PDF. Before these changes, the application would happily cook up a bouncer (sharing) link for you, but that link wouldn't do anything useful.

This PR replaces https://github.com/hypothesis/client/pull/2871

## With these changes...

These changes create a new UI path for both "share this page's annotations" and "share this annotation" when the page's URI or the annotation's URI (respectively) are not web-accessible.

When the page's URI is not web-accessible, using the share-this-page's-annotations button will now result in:

image

When an annotation's URI is not web-accessible, using the share-this-annotation button will now result in:

image

The link provided, as explained, will go to the single-annotation view.

The "panel" that the share-this-annotation content shows up in has been slightly widened—from `20em` to `24em` (with a `max-width` of `85vw` to keep it from getting ungainly on narrow viewports). This accommodates the longer text needed to explain the not-available-in-context wording without risking that this panel on the first annotation in the list could overlap the top bar.

I manually tested that:

* When built into the local extension, local PDF files appropriately get the new, unshareable treatment.
* When built into the local extension, web-hosted PDF files still allow sharing correctly.

Fixes #2786

### CODE REVIEW

**Comment by klemay** [comment]
@lyzadanger nice & elegant solution, IMO! kudos!

File: src/sidebar/components/share-annotations-panel.js [hunk 1]
```diff
@@ -95,7 +98,7 @@ function ShareAnnotationsPanel({ analytics, toastMessenger }) {
             ) : (
               <span>
                 Anyone using this link may view the annotations in the group{' '}
-                <em>{focusedGroup.name}</em>.
+                <em>{focusedGroup?.name}</em>.
```
Comment (robertknight) [inline src/sidebar/components/share-annotations-panel.js:101]: This `?` isn't needed any more.

File: src/sidebar/components/share-annotations-panel.js [hunk 2]
```diff
@@ -59,7 +62,7 @@ function ShareAnnotationsPanel({ analytics, toastMessenger }) {
       title={panelTitle}
       panelName={uiConstants.PANEL_SHARE_ANNOTATIONS}
     >
-      {focusedGroup && mainFrame && (
+      {shareURI && uriShareable && focusedGroup && (
```
Comment (robertknight) [inline src/sidebar/components/share-annotations-panel.js:65]: It seems inconsistent that we could have a `shareURI` defined and yet at the same time a `uriShareable` flag being false. One way to avoid this seeming inconsistency might be to move the logic associated with `uriShareable` into the `pageSharingLink` function, so that `pageSharingLink` returns either a usable URL or `null` if the link is not shareable. Tests for `shareURI && uriShareable` could then become just `shareURI`.

However, you'd need to change the logic for the `These annotations cannot be shared` text so that this content didn't appear if `shareURI` isn't set because the document URI simply isn't known yet (ie. `mainFrame.uri` is not set because eg. the PDF is still loading or document hasn't communicated its URI).

File: src/sidebar/components/share-annotations-panel.js [hunk 3]
```diff
@@ -110,6 +113,14 @@ function ShareAnnotationsPanel({ analytics, toastMessenger }) {
           />
         </div>
       )}
+      {shareURI && !uriShareable && (
```
Comment (robertknight) [inline src/sidebar/components/share-annotations-panel.js:116]: The conditions here imply that we are missing a state for when this panel is shown before the document URI is known (eg. because the document is a PDF that still loading). Currently the output is an empty panel with a title but no content. It might be a bit nicer to show a loading spinner or similar.

File: src/sidebar/components/annotation-share-control.js [hunk 4]
```diff
@@ -141,14 +143,23 @@ function AnnotationShareControl({
...
+                {annotationSharingInfo}
+              </div>
+            ) : (
+              <div className="annotation-share-panel__details">
+                This annotation cannot be shared in its original context because
+                it was made on a document that is not available on the web. This
+                link shares the annotation by itself.
+              </div>
+            )}
+            {inContextAvailable && (
```
Comment (robertknight) [inline src/sidebar/components/annotation-share-control.js:157]: In the case where only the non-incontext link is available, the social media sharing options could still share that.

File: src/sidebar/components/annotation-share-control.js [hunk 5]
```diff
@@ -141,14 +143,23 @@ function AnnotationShareControl({
...
+              <ShareLinks
+                shareURI={shareUri}
+                analyticsEventName={analytics.events.ANNOTATION_SHARED}
```
Comment (robertknight) [inline src/sidebar/components/annotation-share-control.js:160]: This reminds me - perhaps we should just strip out all the "analytics" code for the time being since we're not using any of it.

File: src/sidebar/components/test/annotation-share-control-test.js [hunk 6]
```diff
@@ -195,13 +199,38 @@ describe('AnnotationShareControl', () => {
...
 
-      const permissionsEl = wrapper.find(
-        '.annotation-share-panel__permissions'
-      );
+      const permissionsEl = wrapper.find('.annotation-share-panel__details');
       assert.equal(permissionsEl.text(), testcase.expected);
     });
   });
 
+  it('renders an explanation if annotation cannot be shared in context', () => {
```
Comment (robertknight) [inline src/sidebar/components/test/annotation-share-control-test.js:207]: This test matches the implementation, although I queried whether perhaps we should show these links, just sharing the single annotation page rather than the incontext link.

File: src/sidebar/util/annotation-sharing.js [hunk 7]
```diff
@@ -1,47 +1,74 @@
...
+ * Retrieve an appropriate sharing link for this annotation.
  *
- * @param {HostConfig} settings
- * @return {boolean}
+ * If the annotation is on a shareable document (i.e. its document is
+ * web-accessible), prefer the `incontext` (bouncer) link, but fallback to the
+ * `html` (single-annotation `h` web view) link if needed.
+ *
+ * If the annotation is not on a shareable document, don't use the `incontext`
+ * link as that won't work; only use the single-annotation-view `html` link.
```
Comment (robertknight) [inline src/sidebar/util/annotation-sharing.js:16]: This comment raises an issue - does the backend even attempt to generate an `incontext` link for `file:` URLs? It probably shouldn't.

File: src/sidebar/util/test/annotation-sharing-test.js [hunk 8]
```diff
@@ -24,75 +25,120 @@ describe('sidebar.util.annotation-sharing', () => {
...
-
-      assert.isUndefined(sharingUtil.shareURI(fakeAnnotation));
+  describe('isShareableURI', () => {
+    [
+      'http://www.example.com',
+      'http://www.foo.bar',
+      'http://hi',
+      'http:foo',
+      'https://www.foo.bar/baz/ding.html',
+    ].forEach(validURI => {
```
Comment (robertknight) [inline src/sidebar/util/test/annotation-sharing-test.js:102]: We are assuming here that the protocol will always be lower-case. I think this is the case as long as the document URI comes from the browser itself. I wonder what happens if the document were to contain something like `<link rel="canonical href="HTTPS://WWW.FOOBAR.COM/BAZ">` though. Please don't spend too many cycles worrying about this, it's very much an edge case.

File: src/styles/mixins/molecules.scss [hunk 9]
```diff
@@ -114,9 +114,12 @@
 /**
  * Base styles for a "panel"-like element, with appropriate
  * padding, heading and close-button styles.
+ *
+ * @param {length} [$rhythm] - An optional value to use for vertical rhythm
+ *   (spacing, vertically)
```
Comment (robertknight) [inline src/styles/mixins/molecules.scss:119]: I see you're using JSDoc-style syntax here. The meaning is clear, although I don't know if this is an "officially supported" syntax.

**Review by robertknight — COMMENTED** [review]
The UI changes look good. I left a few comments in the implementation. In particular:

- It may be worth combining the `pageSharingLink` and `isShareableURI` functions
- Should we still show the social media share links if the link is an HTML rather than in-context link?
- What should the panel show if the document URI is not known yet (eg. because it is a PDF that is still loading)?

File: src/sidebar/components/annotation-share-control.js (hunk 4 above)
Comment (lyzadanger) [reply src/sidebar/components/annotation-share-control.js:157]: We don't have the vertical real estate to show them, however, without risking the panel getting too tall and interfering with the top bar. I'm not sure how to reconcile in short order.

File: src/sidebar/components/annotation-share-control.js (hunk 5 above)
Comment (lyzadanger) [reply src/sidebar/components/annotation-share-control.js:160]: I'd be very +1 on that.

File: src/sidebar/util/annotation-sharing.js (hunk 7 above)
Comment (lyzadanger) [reply src/sidebar/util/annotation-sharing.js:16]: IIRC, yes: it will always return an `incontext` (bouncer) link unless the `h` service is not configured with a `bouncer_url`.

File: src/sidebar/util/test/annotation-sharing-test.js (hunk 8 above)
Comment (lyzadanger) [reply src/sidebar/util/test/annotation-sharing-test.js:102]: It would be trivial to make the regexp case-insensitive; good catch.

File: src/styles/mixins/molecules.scss (hunk 9 above)
Comment (lyzadanger) [reply src/styles/mixins/molecules.scss:119]: It's totally a made-up fantasy world use of JSDoc-style comments. However, I wanted to capture this "type" of information and didn't see a built-in way to do it in SCSS source. Open to suggestions.

File: src/sidebar/components/share-annotations-panel.js (hunk 2 above)
Comment (lyzadanger) [reply src/sidebar/components/share-annotations-panel.js:65]: Thanks for calling this out. I think some of this tangle comes organically out of trying to appease type-checking, indirectly. I'll attempt to clarify.

File: src/sidebar/components/share-annotations-panel.js (hunk 3 above)
Comment (lyzadanger) [reply src/sidebar/components/share-annotations-panel.js]: I've rewritten this logic in the newest iteration.

**Comment by lyzadanger** [comment]
@robertknight I've addressed this round of changes, involving:

* Change in logic/state structure in `ShareAnnotationsPanel`. It had become convoluted and wonky in part because I was doing some back-bends to avoid typechecking complaints;
* Relatedly, there is a new utility module with a `notNull` helper for places where typing is missing some clues about context
* Pushed some logic about `isShareableURI` into `getPageSharingLink` as you suggested
* Made `isShareableURI` case-insensitive
* `ShareAnnotationsPanel` will now show a spinner while loading

image

File: src/sidebar/components/share-annotations-panel.js [hunk 10]
```diff
@@ -59,55 +58,70 @@ function ShareAnnotationsPanel({ analytics, toastMessenger }) {
       title={panelTitle}
       panelName={uiConstants.PANEL_SHARE_ANNOTATIONS}
     >
-      {focusedGroup && mainFrame && (
+      {!sharingReady && (
```
Comment (lyzadanger) [inline src/sidebar/components/share-annotations-panel.js:61]: I hope the states are more clear now. There is one top-level branch now: "is shiz loaded enough yet?" and one secondary branch when the answer is "yes": "Do we have a valid share URI?"

File: src/styles/sidebar/components/share-annotations-panel.scss [hunk 11]
```diff
@@ -19,4 +19,12 @@
   &__icon-button {
     @include buttons.button--input;
   }
+
+  // FIXME: Centralize styling of different sizes of Spinner in a reusable
```
Comment (lyzadanger) [inline src/styles/sidebar/components/share-annotations-panel.scss:23]: Note this: spinner sizing is a function of font sizing, as it is in `em`s (which is fine). At some point we should encapsulate some patterns here so that we have the right small set of defined spinner sizes. The spinner at the panel's font size was too small.

**Comment by lyzadanger** [comment]
@robertknight I should point out two things that have _not_ been addressed:

* Pulling out analytics code
* Showing sharing links when using the `html` link

Trying to bound the scope of this work, but if you feel passionately on either of these, let me know.

File: src/sidebar/components/annotation-share-control.js (hunk 4 above)
Comment (robertknight) [reply src/sidebar/components/annotation-share-control.js:157]: Ah OK. The social media sharing options are only a convenience so I don't think it is essential to display them if we're short on space. It would be useful to have a comment in the code to indicate that why they are missing though.

File: src/sidebar/components/share-annotations-panel.js (hunk 10 above)
Comment (robertknight) [reply src/sidebar/components/share-annotations-panel.js:61]: This makes sense to me. If it gets significantly more complex in future that it might help to factor out a helper component in the same module.

File: src/sidebar/util/annotation-sharing.js [hunk 12]
```diff
@@ -1,47 +1,78 @@
...
+ * a specific group (groupID) on a specific document (documentURI). If the
+ * `documentURI` provided is not a web-accessible URL, no link is generated.
+ *
+ * @param {string} documentURI
+ * @param {string} groupID
+ * @return {string}
+ */
+export function pageSharingLink(documentURI, groupID) {
+  if (!isShareableURI(documentURI)) {
+    return '';
```
Comment (robertknight) [inline src/sidebar/util/annotation-sharing.js:43]: This works, although I'd be inclined to return `null` instead and make it more obvious that callers need to handle the case where there is no link.

File: src/sidebar/util/test/annotation-sharing-test.js [hunk 13]
```diff
@@ -24,75 +25,129 @@ describe('sidebar.util.annotation-sharing', () => {
...
+      });
+
+      it('returns `undefined` if links empty', () => {
+        delete fakeAnnotation.links.incontext;
+        delete fakeAnnotation.links.html;
+
+        assert.isUndefined(sharingUtil.annotationSharingLink(fakeAnnotation));
+      });
+
+      it('returns `undefined` if no links on annotation', () => {
```
Comment (robertknight) [inline src/sidebar/util/test/annotation-sharing-test.js:53]: Can this ever actually happen with the API or will it always set `links` but possibly leave the object empty?

File: src/sidebar/util/test/annotation-sharing-test.js [hunk 14]
```diff
@@ -24,75 +25,129 @@ describe('sidebar.util.annotation-sharing', () => {
...
+      });
+
+      it('returns `html` link if set on annotation', () => {
+        assert.equal(
+          sharingUtil.annotationSharingLink(fakeAnnotation),
+          'https://www.example2.com'
+        );
+      });
+
+      it('returns `undefined` no `html` link', () => {
```
Comment (robertknight) [inline src/sidebar/util/test/annotation-sharing-test.js:72]:
```suggestion
      it('returns `undefined` if no `html` link', () => {
```

File: src/sidebar/util/typing.js [hunk 15]
```diff
@@ -0,0 +1,11 @@
+/**
+ * Helper functions for cases in which logically a reference is definitely
```
Comment (robertknight) [inline src/sidebar/util/typing.js:2]:
```suggestion
 * Helper function for cases in which logically a reference is definitely
```

Since this JSDoc refers to one specific function rather than the whole module.

**Review by robertknight — APPROVED** [review]
LGTM with a few minor comments.

File: src/sidebar/util/annotation-sharing.js (hunk 12 above)
Comment (lyzadanger) [reply src/sidebar/util/annotation-sharing.js:43]: When I was writing this, I was half-thinking the same thing, so, yeah, sounds good.

File: src/sidebar/util/test/annotation-sharing-test.js (hunk 13 above)
Comment (lyzadanger) [reply src/sidebar/util/test/annotation-sharing-test.js:53]: I do not know offhand.
