### PR TITLE
Fallback to last text node when we will fall into a null sibling node situation

### LINKED ISSUE #122: Annotate button fails with error when specific phrase is highlighted
### Steps to reproduce
1. Go to http://jonudell.net/h/mueller_01.pdf
2. Select the word "Chomsky", and **only** that word, in the first paragraph. Note that making this selection precisely requires fine mouse control to avoid selecting the whole paragraph
3. Click the "Annotate" button

### Expected behaviour
The word "Chomsky" should be highlighted and a new annotation should be created.

### Actual behaviour
No new annotation is created. An error appears in the dev console:

```
Uncaught TypeError: Cannot read property 'classList' of null
    at getNodeTextLayer (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/injector.bundle.js?bb3e58:683:24)
    at Object.exports.describe (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/injector.bundle.js?bb3e58:934:20)
    at getSelectors (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/injector.bundle.js?bb3e58:1526:29)
    at Array.map (native)
    at PdfSidebar.module.exports.Guest.createAnnotation (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/injector.bundle.js?bb3e58:1550:36)
    at PdfSidebar.module.exports.Sidebar.createAnnotation (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/injector.bundle.js?bb3e58:3043:40)
    at Object.onAnnotate (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/injector.bundle.js?bb3e58:1179:14)
at Adder.handleCommand (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/injector.bundle.js?bb3e58:426:15)
```

### Browser/system information
Chrome v54.0.2816.0
Hypothesis v0.44

### PR DESCRIPTION
**Pull request by sean-roberts**
fixes #122

### CODE REVIEW

File: h/static/scripts/vendor/annotator.js [hunk 1]
```diff
@@ -622,7 +622,7 @@
       }
       nr = {};
       if (r.startOffset > 0) {
-        if (r.start.nodeValue.length > r.startOffset) {
+        if (!r.start.nextSibling || r.start.nodeValue.length > r.startOffset) {
```
Comment (sean-roberts) [inline h/static/scripts/vendor/annotator.js]: That is right, the selector does end up at the empty last node. However, this is ok because our anchoring process seems to be filtering out empty nodes as well. It will not wrap the empty node with spans. So it's really a non-issue right now

File: h/static/scripts/annotator/anchoring/test/pdf-test.js [hunk 2]
```diff
@@ -95,6 +98,35 @@ describe('PDF anchoring', function () {
         });
       });
     });
+
+    it('returns a selector when range stateContainer has no sibling', function(){
```
Comment (sean-roberts) [inline h/static/scripts/annotator/anchoring/test/pdf-test.js]: yeah.... I don't think that's a think we should really care about
