### PR TITLE
Position the adder to the top-left corner on hide

### LINKED ISSUE #3193: Adder affects the responsiveness of the host page
If the adder is displayed to the right or bottom of the host page it retains its position and affects the look of the host page when the window dimensions are reduced.

### Steps to reproduce
1. Select some text on the right or bottom portion of the host page, so that the adder is visible 
2. (optional) click to somewhere in the page to make the adder invisible
3. Resize the window and make it smaller

### Expected behaviour
The addition of the adder to the page at any position should not affect how the page looks when the dimensions are reduced.

### Actual behaviour
Although the adder maybe invisible it retains its absolute position, hence it affects the overall look of the page.

Here is a video:

https://user-images.githubusercontent.com/8555781/112346418-3aa16100-8cc6-11eb-9817-299ca2f4c6c1.mov

In the last segment of the video the adder (hidden) is removed and the page recovers the natural look and feel.

### Browser/system information
Tested on Chrome 91.

### Additional details
Elements with CSS `visibility: hidden` are not shown by the browser maintains its rendering position.

### PR DESCRIPTION
**Pull request by esanzgar**
When the `adder` is hidden reposition the outer container to the
top-left corner of the host page.

I tested this on Safari, Chrome and Firefox and it doesn't affects
negatively the fade-out effect.

Closes #3193

### CODE REVIEW

**Comment by LMS007** [comment]
Sorry, I feel a bit dumb not seeing the difference. I realize the adder is still sitting there, but hidden. I don't see how it affects the layout when resizing? I'm sure you're right, I just wanted to reproduce it on my end. Lets sync up tomorrow.

**Comment by esanzgar** [comment]
@LMS007 Maybe this video could clarify a little bit what I am reporting:

https://user-images.githubusercontent.com/8555781/112482343-40577f00-8d78-11eb-827d-abdb57fb4a0b.mov

You can see that the adder affects the responsiveness of the host page when the window is resized. In some browser it makes the page scrollable (Firefox), in others, like Chrome, the text become smaller.

When clicked on the host page, the adder is hidden but the page still looks wonky.

**Comment by LMS007** [comment]
> @LMS007 Maybe this video could clarify a little bit what I am reporting:
> 
>  Screen.Recording.2021-03-25.at.14.35.10.mov 
> You can see that the adder affects the responsiveness of the host page when the window is resized. In some browser it makes the page scrollable (Firefox), in others, like Chrome, the text become smaller.
> 
> When clicked on the host page, the adder is hidden but the page still looks wonky.

Awe yes I see now.  I had to look at the normal version first with the adder not rendered to the page.

File: src/annotator/test/adder-test.js [hunk 1]
```diff
@@ -367,4 +366,20 @@ describe('Adder', () => {
       );
     });
   });
+
+  describe('#hides', () => {
```
Comment (LMS007) [inline src/annotator/test/adder-test.js:370]:
```suggestion
  describe('#hide', () => {
```

Should match the member name exactly

**Review by LMS007 — APPROVED** [review]
Great fix!

Just change the name of that test, and merge
