### PR TITLE
Fix off-screen empty drafts not being removed when a new annotation is created

### LINKED ISSUE #97: New and empty off-screen annotations do not always get deleted when a new annotation is created
Note: This will not be easily reproducible until https://github.com/hypothesis/client/issues/94 is fixed.

The logic which removes new, empty annotations does not run unless the annotation is in or near the viewport and thus has a corresponding `<annotation>` component instantiated for it. Therefore if a new empty annotation is a long way offscreen, it will not get removed if another new annotation is created.

**Steps to reproduce:**
1. In a page with many annotations, create a new annotation at the top of the page but do not save it
2. Create a new annotation at the bottom of the page

**Expected:**
Annotation created in step (1) is removed

**Actual:**
Annotation created in step (1) is not removed

**Notes**

Now that the state of annotations being edited is maintained entirely in the `drafts` service, we can move this logic outside of the `<annotation>` component and avoid this problem. In order to fix this, we just need to remove any empty drafts when a new annotation is created locally.

### PR DESCRIPTION
**Pull request by robertknight**
The logic to remove new and empty annotations used to live in the
`<annotation>` component because that was the only part of the code that
had access to the state of unsaved changes.

Since `<annotation>` instances are only created for on-screen annotations,
this can result in empty drafts not being removed if the empty
annotation is off-screen.

Now that the canonical content of unsaved annotations is stored in the
drafts service, we can move the logic outside of the annotation
component and fix this problem.

As with https://github.com/hypothesis/client/pull/106, drafts should live in the app state which would make implementing this kind of logic very easy, but that is blocked on other refactoring. This PR at least fixes the issue and documents (via tests) the intended behavior.

Fixes #97

### CODE REVIEW

File: h/static/scripts/root-thread.js [hunk 1]
```diff
@@ -27,6 +27,17 @@ var sortFns = {
 };
 
 /**
+ * Return true if a given `draft` is empty and can be discarded with losing
```
Comment (nickstenning) [inline h/static/scripts/root-thread.js]: *without

File: h/static/scripts/root-thread.js [hunk 2]
```diff
@@ -106,6 +117,19 @@ function RootThread($rootScope, annotationUI, features, searchFilter, viewFilter
     });
   }
 
+  function deleteNewAndEmptyAnnotations() {
+    var newAndEmpty = annotationUI.getState().annotations.filter(function (ann) {
+      if (ann.id) {
```
Comment (nickstenning) [inline h/static/scripts/root-thread.js]: This should probably use `annotationMetadata.isNew`.

File: h/static/scripts/root-thread.js [hunk 3]
```diff
@@ -119,12 +143,17 @@ function RootThread($rootScope, annotationUI, features, searchFilter, viewFilter
     $rootScope.$on(event, function (event, annotation) {
       var annotations = [].concat(annotation);
 
+      if (event.name === events.BEFORE_ANNOTATION_CREATED) {
```
Comment (nickstenning) [inline h/static/scripts/root-thread.js]: We now have two different conditionals in here that check if `event.name === events.BEFORE_ANNOTATION_CREATED`. I think it would make more sense for this event to have a different handler function at this point.

File: h/static/scripts/root-thread.js [hunk 4]
```diff
@@ -27,6 +27,17 @@ var sortFns = {
 };
 
 /**
+ * Return true if a given `draft` is empty and can be discarded with losing
+ * any user input
+ */
+function isEmptyDraft(draft) {
```
Comment (nickstenning) [inline h/static/scripts/root-thread.js]: If there's an easy way to make `isEmpty` the responsibility of the drafts service, I think that would be preferable.

File: h/static/scripts/root-thread.js (hunk 3 above)
Comment (robertknight) [inline h/static/scripts/root-thread.js]: Done, and agreed, this makes things cleaner.

File: h/static/scripts/root-thread.js (hunk 2 above)
Comment (robertknight) [inline h/static/scripts/root-thread.js]: Done

File: h/static/scripts/root-thread.js (hunk 4 above)
Comment (robertknight) [inline h/static/scripts/root-thread.js]: Done - moved to `#getIfNotEmpty` method of drafts service.
