### PR TITLE
Make fetch exceptions consistent and filter them from Sentry

### LINKED ISSUE #2018: Fix Sentry error reports due to unhandled `fetch` failures
Our Sentry error report count from the client has increased significantly recently. From a quick look at the client's [Sentry dashboard](https://sentry.io/organizations/hypothesis/issues/?project=69811&query=is%3Aunresolved) it looks like a large proportion of the reported events are due to unhandled promise rejections arising from `fetch` calls that failed, which have not been handled by an exception handler.

We should audit what happens when various common API calls, especially those made during startup, fail, and check that they don't result in Sentry errors.

We may still want to track the overall _rate_ of these kinds of failures and get notified when it increases unexpectedly, but Sentry is not the right place for that since it isn't a crash due to a fault in the code.

Slack thread: https://hypothes-is.slack.com/archives/CR3E3S7K8/p1586453756008100

----

- [ ] Intercept obvious sources of `fetch` exceptions and make sure we show some visual indication in the UI that something went wrong. Currently almost all errors other than creating, updating or deleting annotations happen silently with only console errors.
- [ ] Ensure that any remaining `fetch` exceptions which are not handled have enough information in their Sentry reports to help us locate the source

### PR DESCRIPTION
**Pull request by lyzadanger**
This PR attempts to stanch the massive flow of fetch exceptions into Sentry by doing two things:

1. Re-throw `fetch` errors in the `api` service so that they have a consistent string prefix. This helps because different browsers format fetch failure exceptions in different ways. It also keeps the exception extant should we wish to handle them higher up in the application.
2. Update `sentry` configuration to ignore errors with that string prefix

It's challenging to test the Sentry logging (or not logging) of `fetch` failures locally, _specifically_, but it is possible to test that thrown exceptions with the filtered error text (`Fetch operation failed`) don't get logged by manually throwing an `Error` with that text somewhere in your local codebase.

See https://stackoverflow.com/c/hypothesis/a/282/6 for how to configure Sentry locally

Fixes #2018

### CODE REVIEW

File: src/sidebar/services/api.js [hunk 1]
```diff
@@ -136,6 +136,12 @@ function createAPICall(
           body: data ? JSON.stringify(stripInternalProperties(data)) : null,
           headers,
           method: descriptor.method,
+        }).catch(err => {
+          // Re-throw Fetch errors such that they all "look the same" (different
+          // browsers throw different Errors on Fetch failure). This allows
+          // Fetch failures to be either handled in particular ways higher up
+          // or for them to be ignored in error reporting (see `sentry` config).
+          throw new Error(`Fetch operation error: ${err}`);
```
Comment (lyzadanger) [inline src/sidebar/services/api.js:144]: I have zero attachment to this string or structure; feel free to suggest alternatives

File: src/sidebar/util/test/sentry-test.js [hunk 2]
```diff
@@ -75,6 +75,20 @@ describe('sidebar/util/sentry', () => {
       );
     });
 
+    it('configures Sentry to ignore Errors with matching the text "Fetch operation failed"', () => {
```
Comment (lyzadanger) [inline src/sidebar/util/test/sentry-test.js:78]: These tests are a little...less than totally useful, but I'm happy to play along!

File: src/sidebar/util/sentry.js [hunk 3]
```diff
@@ -51,6 +51,8 @@ export function init(config) {
   Sentry.init({
     dsn: config.dsn,
     environment: config.environment,
+    // Do not log Fetch failures to avoid inundating with unhandled fetch exceptions
+    ignoreErrors: ['Fetch operation failed'],
```
Comment (robertknight) [inline src/sidebar/util/sentry.js:55]: This string doesn't match the prefix of errors added in `api.js` (the last word here is "failed" but there it is "error").

File: src/sidebar/services/api.js (hunk 1 above)
Comment (robertknight) [reply src/sidebar/services/api.js:144]: Looking at existing reports on Sentry, the error thrown by `fetch` doesn't have any useful information so it might not be worth capturing here. It would be useful to capture the base URL (`url` variable in this context) though. Perhaps create an `Error` subclass?

File: src/sidebar/util/sentry.js (hunk 3 above)
Comment (lyzadanger) [reply src/sidebar/util/sentry.js:55]: :facepalm: D'oh. I was doing some last-minute string changing...

**Comment by lyzadanger** [comment]
> Looking at existing reports on Sentry, the error thrown by fetch doesn't have any useful information so it might not be worth capturing here. It would be useful to capture the base URL (url variable in this context) though. Perhaps create an Error subclass?

`url` or `apiUrl`?

**Comment by lyzadanger** [comment]
@robertknight Would you be amenable to waiting on the Error subclass until we need it?

**Comment by robertknight** [comment]
I'm going to go ahead and merge this so we have more time to gather data on whether it helps with preventing spamming Sentry.
