### PR TITLE
Add defaultContentFrame store selector to fix importing to VitalSource

### LINKED ISSUE #5772: Verify that imported annotations in VitalSource include the right document metadata
When importing annotations into a document, we use the store's `mainFrame` to get the document URI and other document metadata.

Verify that this is the right approach when importing annotations into VitalSource documents.

### PR DESCRIPTION
**Pull request by acelaya**
Closes #5772 

VitalSource docs do not have a `mainFrame`, but they do have a single frame with `id`.

This PR adds a new `defaultContentFrame` store selector which is the equivalent of `store.mainFrame() ?? store.frames()[0]`, and can be used consistently to determine the frame from which we should get metadata when importing annotations for pages, PDFs and VitalSource books.

This new selector can be useful in other places of the code, but I will check and refactor that on a follow-up PR.

### CODE REVIEW

File: src/sidebar/store/modules/frames.ts [hunk 1]
```diff
@@ -147,7 +150,20 @@ const mainFrame = createSelector(
...
   // one with a `null` id.
-  frames => frames.find(f => !f.id) || null,
+  firstFrameWithoutId,
+);
+
+/**
+ * Return the "main" frame that the sidebar is connected to, falling back to the
+ * first available frame.
+ * For VitalSource books, we don't have a mainFrame, but we do have a single
+ * frame on the list.
```
Comment (robertknight) [inline src/sidebar/store/modules/frames.ts:160]: This describes the implementation, but I'd like to try and reword this to differentiate it a bit more clearly from `mainFrame`. How about:

"Return the default frame that annotations are assumed to be associated with, if they can't be matched to a more specific frame.

For most document types this is the same as ({@see mainFrame}), but for eg. VitalSource books there is no main frame, but instead only a frame with the current chapter content." 

This aligns with the similar logic in `frameForAnnotation` in `services/frame-sync.ts`.

**Review by robertknight — APPROVED** [review]
LGTM, but I suggested some revisions to the description.
