### PR TITLE
Remove `unloadAnnotations` method from `annotation-mapper`

### LINKED ISSUE #1879: Exception when applying annotation deletion received over WebSocket
**Steps to reproduce**

1. Open two tabs, A and B, at the same URL and activate the Hypothesis client in both
1. In tab A, add an annotation
1. Switch to tab B and click the red button at the top of the sidebar to apply updates. Select the tab containing the new annotation
1. In tab A, remove the annotation
1. Switch to tab B and click the red button to apply updates

**Expected results**

The annotation should disappear in tab B and the red icon in the toolbar should disappear.

**Actual results**

The annotation disappears but the annotation count for the tab retains its old value, the red icon in the toolbar remains visible and the UI "freezes" in that it stops responding to most input.

Screenshot 2020-03-06 12 49 36

Apply deletes error

**Notes**

Client version: v1.339.0-df87208f (same as v1.340.0)

### PR DESCRIPTION
**Pull request by robertknight**
This method inadvertently (?) mutated annotations in the store which
caused a crash later. Ultimately this method dispatched an event which
was handled only in one place in `root-thread.js` to call
`store.removeAnnotations()`.

This commit removes the method and associated `ANNOTATIONS_UNLOADED`
event and replaces callers with direct calls to
`store.removeAnnotations(...)`.

All uses of Angular events will soon need to be removed as part of the
migration away from Angular JS, but that will happen separately.

Fixes #1879

### CODE REVIEW

File: src/sidebar/store/modules/annotations.js [hunk 1]
```diff
@@ -12,6 +12,9 @@ import * as util from '../util';
 /**
  * Return a copy of `current` with all matching annotations in `annotations`
  * removed.
+ *
+ * Annotations in `annotations` may be complete annotations or "stubs" with only
+ * the `id` field set.
  */
 function excludeAnnotations(current, annotations) {
```
Comment (lyzadanger) [inline src/sidebar/store/modules/annotations.js]: Given that this function's only caller is `removeAnnotations`, I think it could be further refactored for clarity or even integrated into `removeAnnotations`. That's a separate task, though!
