### PR TITLE
Correctly select Orphan tab when viewing direct-linked orphan

### LINKED ISSUE #2686: Following bouncer links to orphaned annotations is broken
Screenshot from 2020-10-28 15-40-24

Example: https://hyp.is/8VgUcHvgTvuTR1eQizPISg/www.thelegalproject.nl/

1. Click on a bouncer link to an orphaned annotation
2. Expected result: The client should open and show the annotation somehow  
   Actual result: The client says "Showing 1 annotation" and "Show all (0)" but doesn't show the annotation. If you click <kbd>Show all</kbd> the annotation can be found under the _Orphans_ tab

### PR DESCRIPTION
**Pull request by lyzadanger**
Previously, tab selection for direct-linked annotations was happening
before anchoring was complete—that means that orphaned annotations had
not yet been marked as being orphans (`$orphan`). Make sure that
direct-linked tab selection is checked any time the direct-linked
annotation changes.

Also fix a UI confusion in which the "Show All" button would show
the count of all annotations in this (direct-linked) state, which is
confusing because orphans don't count toward "All annotations" (nor do
page notes, FWIW).

To reproduce/test locally:

* General an orphaned annotation in your local env. If you don't have one, you can create one by editing the source of any of the HTML sample pages to add a little text, restarting dev server, selecting your added text and annotating it, then removing that text from the HTML source. 
* Make sure `bouncer` and `via` (legacy) are running locally.
* View your local, orphaned annotation and copy its share link from the share button on the annotation card.
* Paste that link into your browser

Before:

image

After:

image

Fixes #2686

### CODE REVIEW

File: src/sidebar/components/sidebar-view.js [hunk 1]
```diff
@@ -122,8 +124,17 @@ function SidebarView({
...
       selectTab(directLinkedTab);
+    } else if (linkedAnnotation) {
+      // Make sure to allow for orphaned annotations (which won't have an anchor)
+      selectTab(directLinkedTab);
     }
-  }, [directLinkedTab, frameSync, linkedAnnotationAnchorTag, selectTab]);
+  }, [
+    directLinkedTab,
+    frameSync,
+    linkedAnnotation,
```
Comment (lyzadanger) [inline src/sidebar/components/sidebar-view.js:134]: By adding `linkedAnnotation` to the dependencies here, tab selection will be re-evaluated on the change of `$orphan: true` on orphaned annotations. Otherwise this executes prematurely.

File: src/sidebar/components/filter-status.js [hunk 2]
```diff
@@ -134,9 +135,9 @@ function SelectionFilterStatus({ filterState, rootThread }) {
   // Because of the confusion between counts of entities between selected
   // annotations and filtered annotations, don't display the total number
   // when in user-focus mode because the numbers won't appear to make sense.
-  const buttonText = filterState.focusConfigured
-    ? 'Show all'
-    : `Show all (${totalCount})`;
+  // Don't display total count, either, when viewing a direct-linked annotation.
```
Comment (LMS007) [inline src/sidebar/components/filter-status.js:138]: could this just say?

"... when in user-focus mode [or when viewing a direct-linked annotation] because the numbers won't appear to `make sense."

**Review by LMS007 — APPROVED** [review]
Code looks solid, I can't confirm this fully works locally for me today, but I don't want to hold up this straight-forward PR for my issues.
