### PR TITLE
Re-render Adder when `annotationsForSelection` property changes

### LINKED ISSUE #3293: Adder points outside the selected text
In some situations the up/down-pointing arrow in the adder is positioned incorrectly and does not point at the end of the selection as expected. This happens when switching between making a selection that contains no existing highlights, and making a selection that does contain an existing highlight.

### Steps to reproduce
1. Select a small portion of text that doesn't contain a highlight
2. Select another portion of text that already contains a highlight

### Expected behaviour
The adder should point towards the last portion of the selected text in both cases.

### Actual behaviour
The adder in the second selection points out of the selected text.

https://user-images.githubusercontent.com/8555781/114714938-ddcc2000-9d32-11eb-8029-971ebff7cc16.mov

### Additional details
When selecting text that already contains annotations the adder shows an extra button `Show X` which adds to the overall dimension of the adder. After the annotation is created the adder is hidden but the dimensions of the adder is retained.

The calculation for the placement of the adder is based on the dimensions of the previously shown adder. Selecting alternatively between text that contains highlights or not, exposes this behaviour.

One solution could be:
1. While the adder is still hidden, toggle off/on the `Show X`, depending if the selected text contains highlights.
2. Calculate the size of the adder and, based on that, the placement of the adder.
3. Show the adder.

### PR DESCRIPTION
**Pull request by robertknight**
This fixes an issue where the `show` method could position the adder
incorrectly if the emptiness of `annotationsForSelection` changed since
the adder was previously displayed. This is because the size of the
adder was outdated at the point when `show` calls `_calculateTarget` to
determine the adder position. Re-rendering as soon as
`annotationsForSelection` changes resolves this.

Fixes #3293

**TODO:**

- [x] Add a test

### CODE REVIEW

**Comment by lyzadanger** [comment]
@robertknight Pretty sure you meant to assign me as a reviewer, not to the PR itself, so have updated assignments accordingly :)

File: src/annotator/adder.js [hunk 1]
```diff
@@ -127,17 +127,31 @@ export class Adder {
...
+  get annotationsForSelection() {
+    return this._annotationsForSelection;
+  }
+
+  /**
+   * Set the annotation IDs associated with the current selection.
+   *
+   * Setting this to a non-empty list causes the "Show" button to appear in
+   * the toolbar, triggering the `onShowAnnotations` callback passed to the
+   * constructor when clicked.
```
Comment (lyzadanger) [inline src/annotator/adder.js:148]:
```suggestion
   * Setting this to a non-empty list causes the "Show" button to appear in
   * the toolbar. Clicking the "Show" button  triggers the `onShowAnnotations`
   * callback passed to the constructor.
```

File: src/annotator/adder.js [hunk 2]
```diff
@@ -127,17 +127,31 @@ export class Adder {
...
+   */
+  set annotationsForSelection(ids) {
+    this._annotationsForSelection = ids;
+    this._render();
```
Comment (lyzadanger) [inline src/annotator/adder.js:152]: Glad we don't have to be responsible for manual rendering in most of the app :).

**Review by lyzadanger — APPROVED** [review]
Nice fix for a little nit.
