### PR TITLE
Fix OAuth popup being blocked by pop-up blocker in Firefox and IE

### LINKED ISSUE #534: "Log in" button triggers popup blocker in Firefox
**Steps to reproduce:**

1. Go to https://hypothes.is/docs/help?__feature__[client_oauth]=1
2. Click the "Log in" button in the client

**Expected result:** A login popup window appears and then either prompts for login details or immediately disappears and logs the user in.

**Actual result:** A "Firefox prevented this site from opening a pop-up window" message appears.

**Notes:**

- Clicking the "Preferences" button in the message bar and selecting "Allow pop-ups for ..." results in the login popup appearing.
- The pop-up blocker is not triggered by the same actions in Chrome and Safari.

### PR DESCRIPTION
**Pull request by robertknight**
When the user clicked the "Log in" link, the URL of the
"oauth.authorize" endpoint was fetched via an async Promise-returning
method before the `window.open` call was made. This meant that the
`window.open` call did not happen in the turn of the event loop that was
triggered by the user action and so Firefox & IE's popup blockers deemed
the call to have happened outside the context of a user gesture and
prevented the window being opened.

Chrome, Safari & Edge have different heuristics and did not block the
popup before.

Fix the issue by opening the window directly when the user clicks on the
"Log in" button, at a dummy URL ("about:blank"), and then changing the
window's location once the authorization endpoint URL has been fetched.

Fixes #534

**Testing note:** OAuth login does not yet work in IE for other reasons which will be fixed separately, so for the moment, just test following the steps in #534.

### CODE REVIEW

**Comment by seanh** [comment]
Confirmed that I can reproduce the issue in master and that this fixes it. Also that this branch still works fine  in Chrome too

File: src/sidebar/oauth-auth.js [hunk 1]
```diff
@@ -337,6 +337,27 @@ function auth($http, $rootScope, $window,
     var left   = $window.screen.width / 2 - width / 2;
     var top    = $window.screen.height /2 - height / 2;
 
+    var authWindowSettings = queryString.stringify({
+      left: left,
+      top: top,
+      width: width,
+      height: height,
+    }).replace(/&/g, ',');
```
Comment (seanh) [inline src/sidebar/oauth-auth.js]: For readability I think it'd be worth moving this into a `strWindowFeatures(obj)` function, or else just adding a code comment, I had to debug this and look into the `window.open` docs to figure out what was going on

File: src/sidebar/oauth-auth.js [hunk 2]
```diff
@@ -337,6 +337,27 @@ function auth($http, $rootScope, $window,
...
+
+    // Open the auth window before fetching the `oauth.authorize` URL to ensure
+    // that the `window.open` call happens in the same turn of the event loop
+    // that was initiated by the user clicking the "Log in" link.
+    //
+    // Otherwise the `window.open` call is not deemed to be in response to a
+    // user gesture in Firefox & IE 11 and their popup blocking heuristics will
+    // prevent the window being opened. See
+    // https://github.com/hypothesis/client/issues/534 and
+    // https://github.com/hypothesis/client/issues/535.
```
Comment (seanh) [inline src/sidebar/oauth-auth.js]: Very good to have this comment here

File: src/sidebar/oauth-auth.js (hunk 1 above)
Comment (robertknight) [reply src/sidebar/oauth-auth.js]: I added a comment. This legacy API unfortunately has a somewhat suboptimal interface.
