### PR TITLE
Fix behavior when there are multiple unsaved annotations

### LINKED ISSUE #94: Creating new annotations destroys existing unsaved ones
1. Create a new annotation, but don't save it and don't enter any text or tags.
2. Create another new annotation.

Expected: Annotation 1 should be deleted, I should see annotation 2 in the sidebar.

Actual: Annotation 1 is deleted but I do not see annotation 2 in the sidebar.

peek 2016-09-09 18-12

Second version of the same bug:

1. Create a new annotation, this time do enter some text and tags into it, but don't save it
2. Create another new annotation

Expected: I think the expected behaviour in this case is that I should see both annotations 1 and 2 in the sidebar?

Actual: annotation 1 is deleted, I see only annotation 2 in the sidebar.

peek 2016-09-09 18-27

The first issue bisects to this commit https://github.com/hypothesis/client/commit/1832a97c314f1c8c7f07229266e817b41c026328 and I suspect  the second issue is just another symptom of the same bug

### PR DESCRIPTION
**Pull request by robertknight**
Fix missing initialization of $orphan flag for new annotations and
properly account for annotations that do not have IDs in ADD_ANNOTATIONS
and UPDATE_ANCHOR_STATUS actions.

 - Fix ADD_ANNOTATIONS action replacing the first existing unsaved
   annotation when a second unsaved annotation is added
 - Fix UPDATE_ANCHOR_STATUS action not matching annotations without
   IDs (ie. new annotations) correctly.
 - Fix $orphan flag not being initialized for new annotations

Fixes #94

----

- [x] Actually implement the tests as described in the comments

### CODE REVIEW

File: h/static/scripts/annotation-ui.js [hunk 1]
```diff
@@ -141,6 +141,27 @@ function findByTag(annotations, tag) {
...
+  }
+
+  // Currently the user ID, permissions and group of new annotations are
+  // initialized in the <annotation> component controller because the session
+  // state and focused group are not stored in the Redux store. Once they are,
+  // that initialization should be moved here.
+
+  return Object.assign({}, annotation, {
+    // Copy $$tag explicitly because it is non-enumerable
+    $$tag: annotation.$$tag,
```
Comment (robertknight) [inline h/static/scripts/annotation-ui.js]: This is obviously a bit silly. I intend to refactor the way local tags are assigned to annotations to avoid the need for this, and probably also change it from `$$tag` to just `$tag`. That is outside the scope of this PR though.

**Comment by nickstenning** [comment]
LGTM.
