### PR TITLE
Move the logic that updates the focused group for new annotations

### LINKED ISSUE #105: New annotations that are scrolled off-screen are not moved to the current group when switching groups
**Steps to reproduce**

1. Go to example.com, select the 'Public' group and switch to the Page Notes tab, where Jon has helpfully posted several hundred notes
2. Create a new page note, which should appear at the bottom of the sidebar, and enter some text
3. Scroll to the top of the sidebar
4. Switch to a private group

**Expected**
Page note moves to private group

**Actual**
Page note remains public

**Notes**
Since we now only create `<annotation>` components for annotations that are actually in/near the viewport, we no longer listen for GROUP_FOCUSED or BEFORE_ANNOTATION_CREATED events for annotations that are off-screen, resulting in the group not being updated.

The fix is to move this logic out of the `<annotation>` component. Ideally if the current focused group was a piece of state in the Redux store and GROUP_FOCUSED was an action, then the handler for that action could update this state.

### PR DESCRIPTION
**Pull request by robertknight**
_**This depends on https://github.com/hypothesis/client/pull/110**_

Move the logic that updates the focused group for new annotations
out of the `<annotation>` component and into a service.

This fixes the issue where the event handler does not get invoked if no
`<annotation>` component instance exists for an annotation because it is
currently scrolled off-screen.

As with https://github.com/hypothesis/client/pull/107, this logic should ideally live in a reducer, such that a group change triggers a `GROUP_FOCUSED` action and everything in the app gets updated accordingly. That's not currently possible because that state doesn't live in the app state store. This PR fixes the issue and updates the tests in a way that should be straightforward to adapt in future.

Fixes #105

### CODE REVIEW

File: h/static/scripts/root-thread.js [hunk 1]
```diff
@@ -150,6 +151,26 @@ function RootThread($rootScope, annotationUI, features, searchFilter, viewFilter
     annotationUI.removeAnnotations(annotations);
   });
 
+  // Once https://github.com/hypothesis/client/pull/104 is merged the focused
+  // group state should be moved to the app state store, and then the logic in
+  // this event handler can be moved to the annotations reducer.
+  $rootScope.$on(events.GROUP_FOCUSED, function () {
+    var focusedGroup = groups.focused();
```
Comment (nickstenning) [inline h/static/scripts/root-thread.js]: Is there a reason you wouldn't use the group id carried with the event?

Comment (robertknight) [inline h/static/scripts/root-thread.js]: No and good point. I have updated this to use the group ID from the event.
