### PR TITLE
Fixing sidebar not closing on outside content click issue

### LINKED ISSUE #252: Tapping on page content doesn't auto-close sidebar
_Originally reported as https://github.com/hypothesis/h/issues/3398 by me._

### Steps to reproduce
1. Visit an annotated page in Mobile Safari on iOS
2. Open the sidebar
3. Tap (anywhere) on the content, outside the sidebar.
### Expected behaviour

The sidebar should close.
### Actual behaviour

The sidebar remains open. If you want to close it you need to tap on the "close" arrow button.
### Browser/system information

Mobile Safari, iOS 9.2?

This issue was split out from #2811.

### PR DESCRIPTION
**Pull request by sean-roberts**
Fixes #252 

Since click is not registered for elements without `cursor: pointer` we will listen for the touchstart in addition to the click event so we can get around this issue for mobile devices.

### CODE REVIEW

File: src/annotator/sidebar.coffee [hunk 1]
```diff
@@ -47,6 +47,16 @@ module.exports = class Sidebar extends Host
     @element.on 'click', (event) =>
       if !@selectedTargets?.length
         this.hide()
+
+    # Mobile browsers do not register click events on
```
Comment (robertknight) [inline src/annotator/sidebar.coffee]: I thought that this restriction applied only to iOS but not to Android Chrome. This works either way.
