### PR TITLE
Tweak notebook close button so that it's less obvious that it renders over other modals inside the iframe

### LINKED ISSUE #3676: Notebook close button visible over dialog backdrop
The Notebook's close icon is visible over the backdrop of modal dialogs. See the "X" on the right-hand side of this screenshot:

Dialog backdrop

The desired behavior is that the "X" is rendered underneath the backdrop.

Steps to reproduce:

1. Open the notebook via Account => Open Notebook in the sidebar
2. Click on the Delete icon for one of your annotations

### PR DESCRIPTION
**Pull request by acelaya**
This is another attempt to fix #3676

In this case, this solution does not try to actually solve the problem, as attempted in #5139, because the changes needed are too much.

Instead, this just tweaks the "visuals" of the notebook close button, by removing `variant="dark"`, so that it is less obvious that it is rendered over the "delete annotation" modal. It's still on top, but it's visually "less ugly".

https://user-images.githubusercontent.com/2719332/214013575-f6c793b0-2578-4169-a556-0cf713e187fb.mp4

### CODE REVIEW

File: src/annotator/components/NotebookModal.tsx [hunk 1]
```diff
@@ -120,11 +120,7 @@ export default function NotebookModal({
     >
       <div className="relative w-full h-full" data-testid="notebook-inner">
         <div className="absolute right-0 m-3">
-          <IconButton
-            title="Close the Notebook"
-            onClick={onClose}
-            variant="dark"
-          >
+          <IconButton title="Close the Notebook" onClick={onClose}>
```
Comment (lyzadanger) [inline src/annotator/components/NotebookModal.tsx:123]: I think we can find a styling middle ground here! What we can do is:

* Make it so the button does not have a background color when "at rest", so that it does not interfere with modal overlays
* But still use the `dark` variant color scheme overall, including the visually-helpful hover background color.

We could do this:

```suggestion
          <IconButton
            title="Close the Notebook"
            variant="dark"
            onClick={onClose}
            classes={classnames(
              // Remove the dark variant's background color to avoid
              // interfering with modal overlays. Re-activate the dark variant's
              // background color on hover.
              // See https://github.com/hypothesis/client/issues/3676
              '!bg-transparent enabled:hover:!bg-grey-3'
            )}
          >
```

I wish we could use a single `!important` rule but AFAIK there are no Tailwind utility classes for "not-hovered", so here we turn off all backgrounds and then turn them back on for one specific case.

Of course we want to use `!important` rules very sparingly, but I think this is the proper use case: this is indeed a hack and we want the overriding `!important` rules to stand out. I also think it's a good idea to leave breadcrumbs behind about _why_ we're manually overriding here, ergo the link to the original issue in comments.

The different variants and how `classes` works with components is document in the `frontend-shared` package's pattern library (including a page outlining how to customize or override component styling) — let me know if I can guide further or if any of that it completely non-sensical!

**Review by lyzadanger — CHANGES_REQUESTED** [review]
Good work tracking down how this might be addressed by tweaking component props and variants! Take a look at my suggestion and see what you think.

File: src/annotator/components/NotebookModal.tsx (hunk 1 above)
Comment (acelaya) [reply src/annotator/components/NotebookModal.tsx:123]: Thanks!

Comment (acelaya) [reply src/annotator/components/NotebookModal.tsx]: I like the approach. Pushed!

**Review by lyzadanger — APPROVED** [review]
👍🏻
